name: Release Higgs Shop

on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: 'Do a dry run to preview instead of a real release [true/false]'
                required: true
                default: 'true'

defaults:
      run:
        working-directory: core-sdk-samples/higgs-shop-sample-app

jobs:
    confirm-main-branch:
        name: Confirm release is run on public/main branch
        runs-on: macOS-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Branch name
              run: |
                  BRANCHNAME=${GITHUB_REF##*/}
                  echo "confirming branch name, branch name is:"
                  echo $BRANCHNAME
                  if [ $BRANCHNAME != "main" ]
                  then
                    echo "You can only run a release from the main branch, you are trying to run it from ${BRANCHNAME}"
                    exit 1
                  fi

    release:
        name: Perform Release
        runs-on: macOS-latest
        needs: confirm-main-branch
        env:
            GIT_AUTHOR_NAME: mparticle-bot
            GIT_AUTHOR_EMAIL: developers@mparticle.com
            GIT_COMMITTER_NAME: mparticle-bot
            GIT_COMMITTER_EMAIL: developers@mparticle.com

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Release --dry-run
              if: ${{ github.event.inputs.dryRun == 'true'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
              run: |
                npx \
                -p lodash \
                -p semantic-release@17 \
                -p @semantic-release/changelog@5 \
                -p @semantic-release/git@9 \
                -p @semantic-release/exec@5 \
                semantic-release \
                --dry-run --branches main

            - name: Release
              if: ${{ github.event.inputs.dryRun == 'false'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
              run: |
                npx \
                -p lodash \
                -p semantic-release@17 \
                -p @semantic-release/changelog@5 \
                -p @semantic-release/git@9 \
                -p @semantic-release/exec@5 \
                semantic-release \
                --branches main
